services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}:27017/bookmarks
    ports:
      - 3000:3000
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    image: mongo:8.0.3
    environment:
      - MONGO_INITDB_DATABASE=bookmarks
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USER
      - MONGO_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-data:
